name: PR Continuous Integration checks

on:
  pull_request:
      types:
        - ready_for_review

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install ruff
        run: curl -LsSf https://astral.sh/ruff/install.sh | sh
      # Linter
      - name: Run Ruff linter
        run: ruff check --output-format=github .
      # Formatter
      - name: Run Ruff formatter
        run: ruff format --check .
